/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PhotoPhotoIdRouteImport } from './routes/photo.$photoId_'
import { Route as PhotoPhotoIdEditRouteImport } from './routes/photo.$photoId.edit'

const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotoPhotoIdRoute = PhotoPhotoIdRouteImport.update({
  id: '/photo/$photoId_',
  path: '/photo/$photoId',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotoPhotoIdEditRoute = PhotoPhotoIdEditRouteImport.update({
  id: '/photo/$photoId/edit',
  path: '/photo/$photoId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/feed': typeof FeedRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/upload': typeof UploadRoute
  '/photo/$photoId': typeof PhotoPhotoIdRoute
  '/photo/$photoId/edit': typeof PhotoPhotoIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/feed': typeof FeedRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/upload': typeof UploadRoute
  '/photo/$photoId': typeof PhotoPhotoIdRoute
  '/photo/$photoId/edit': typeof PhotoPhotoIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/feed': typeof FeedRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/upload': typeof UploadRoute
  '/photo/$photoId_': typeof PhotoPhotoIdRoute
  '/photo/$photoId/edit': typeof PhotoPhotoIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/feed'
    | '/login'
    | '/signup'
    | '/unauthorized'
    | '/upload'
    | '/photo/$photoId'
    | '/photo/$photoId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/feed'
    | '/login'
    | '/signup'
    | '/unauthorized'
    | '/upload'
    | '/photo/$photoId'
    | '/photo/$photoId/edit'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/feed'
    | '/login'
    | '/signup'
    | '/unauthorized'
    | '/upload'
    | '/photo/$photoId_'
    | '/photo/$photoId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  FeedRoute: typeof FeedRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  UploadRoute: typeof UploadRoute
  PhotoPhotoIdRoute: typeof PhotoPhotoIdRoute
  PhotoPhotoIdEditRoute: typeof PhotoPhotoIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photo/$photoId_': {
      id: '/photo/$photoId_'
      path: '/photo/$photoId'
      fullPath: '/photo/$photoId'
      preLoaderRoute: typeof PhotoPhotoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photo/$photoId/edit': {
      id: '/photo/$photoId/edit'
      path: '/photo/$photoId/edit'
      fullPath: '/photo/$photoId/edit'
      preLoaderRoute: typeof PhotoPhotoIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  FeedRoute: FeedRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  UploadRoute: UploadRoute,
  PhotoPhotoIdRoute: PhotoPhotoIdRoute,
  PhotoPhotoIdEditRoute: PhotoPhotoIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
